# ArUco Detector Configuration

## Marker Parameters
marker_size: 20  # Size of the ArUco marker in cm

## ArUco Dictionary Selection
# Options: DICT_4X4_50, DICT_4X4_100, DICT_4X4_250, DICT_4X4_1000,
#          DICT_5X5_50, DICT_5X5_100, DICT_5X5_250, DICT_5X5_1000,
#          DICT_6X6_50, DICT_6X6_100, DICT_6X6_250, DICT_6X6_1000,
#          DICT_7X7_50, DICT_7X7_100, DICT_7X7_250, DICT_7X7_1000,
#          DICT_ARUCO_ORIGINAL


aruco_dictionary: DICT_5X5_50  # ArUco marker dictionary to use
## Frame IDs
marker_frame_id: aruco_marker
camera_frame_id: camera_link
