groups:
  - group_name: platform
    markers:
      - id: 0
        size: 0.5
        position: [0.0, 0.0, 0.0]
        orientation: [0.0, 0.0, 0.0] # r, p, y
      - id: 17
        size: 0.25
        position: [-0.6, 0.6, 0.0]
        orientation: [0.0, 0.0, 0.0]
      - id: 22
        size: 0.25
        position: [0.6, 0.6, 0.0]
        orientation: [0.0, 0.0, 0.0]
      - id: 42
        size: 0.25
        position: [0.6, -0.6, 0.0]
        orientation: [0.0, 0.0, 0.0]
      - id: 37
        size: 0.25
        position: [-0.6, -0.6, 0.0]
        orientation: [0.0, 0.0, 0.0]
